# Generated by Django 5.1.6 on 2025-04-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_remove_profile_experience_profile_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='duration_years',
            new_name='years',
        ),
    ]
