# Generated by Django 5.1.6 on 2025-04-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_duration_years_experience_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField()),
                ('terms_of_contract', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(limit_choices_to={'user__user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.profile')),
                ('required_skills', models.ManyToManyField(related_name='projects', to='home.tag')),
            ],
        ),
    ]
