# Generated by Django 5.1.6 on 2025-04-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='home.tag'),
        ),
    ]
