# Generated by Django 5.1.6 on 2025-04-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_matchrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='required_skills',
        ),
    ]
