# Generated by Django 5.1.6 on 2025-04-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_profile_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_project_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='terms_and_conditions',
        ),
    ]
